import subprocess

def all(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/all/0/0-1.txt > diff/' + str(num) + '/0-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-1.txt > diff/' + str(num) + '/1-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-2.txt > diff/' + str(num) + '/1-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-3.txt > diff/' + str(num) + '/1-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-4.txt > diff/' + str(num) + '/1-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-5.txt > diff/' + str(num) + '/1-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-6.txt > diff/' + str(num) + '/1-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-7.txt > diff/' + str(num) + '/1-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-8.txt > diff/' + str(num) + '/1-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-9.txt > diff/' + str(num) + '/1-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-10.txt > diff/' + str(num) + '/1-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-11.txt > diff/' + str(num) + '/1-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/1/1-12.txt > diff/' + str(num) + '/1-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/2/2-1.txt > diff/' + str(num) + '/2-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/2/2-2.txt > diff/' + str(num) + '/2-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/2/2-3.txt > diff/' + str(num) + '/2-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/2/2-4.txt > diff/' + str(num) + '/2-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/2/2-5.txt > diff/' + str(num) + '/2-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-1.txt > diff/' + str(num) + '/3-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-2.txt > diff/' + str(num) + '/3-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-3.txt > diff/' + str(num) + '/3-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-4.txt > diff/' + str(num) + '/3-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-5.txt > diff/' + str(num) + '/3-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-6.txt > diff/' + str(num) + '/3-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-7.txt > diff/' + str(num) + '/3-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-8.txt > diff/' + str(num) + '/3-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-9.txt > diff/' + str(num) + '/3-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-10.txt > diff/' + str(num) + '/3-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-11.txt > diff/' + str(num) + '/3-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-12.txt > diff/' + str(num) + '/3-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-13.txt > diff/' + str(num) + '/3-13.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-14.txt > diff/' + str(num) + '/3-14.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-15.txt > diff/' + str(num) + '/3-15.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-16.txt > diff/' + str(num) + '/3-16.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-17.txt > diff/' + str(num) + '/3-17.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-18.txt > diff/' + str(num) + '/3-18.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-19.txt > diff/' + str(num) + '/3-19.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-20.txt > diff/' + str(num) + '/3-20.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-21.txt > diff/' + str(num) + '/3-21.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-22.txt > diff/' + str(num) + '/3-22.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-23.txt > diff/' + str(num) + '/3-23.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-24.txt > diff/' + str(num) + '/3-24.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-25.txt > diff/' + str(num) + '/3-25.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/3/3-26.txt > diff/' + str(num) + '/3-26.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-1.txt > diff/' + str(num) + '/4-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-2.txt > diff/' + str(num) + '/4-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-3.txt > diff/' + str(num) + '/4-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-4.txt > diff/' + str(num) + '/4-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-5.txt > diff/' + str(num) + '/4-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-6.txt > diff/' + str(num) + '/4-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-7.txt > diff/' + str(num) + '/4-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-8.txt > diff/' + str(num) + '/4-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-9.txt > diff/' + str(num) + '/4-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-10.txt > diff/' + str(num) + '/4-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-11.txt > diff/' + str(num) + '/4-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-12.txt > diff/' + str(num) + '/4-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/4/4-13.txt > diff/' + str(num) + '/4-13.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-1.txt > diff/' + str(num) + '/5-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-2.txt > diff/' + str(num) + '/5-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-3.txt > diff/' + str(num) + '/5-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-4.txt > diff/' + str(num) + '/5-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-5.txt > diff/' + str(num) + '/5-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-6.txt > diff/' + str(num) + '/5-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-7.txt > diff/' + str(num) + '/5-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-8.txt > diff/' + str(num) + '/5-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-9.txt > diff/' + str(num) + '/5-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-10.txt > diff/' + str(num) + '/5-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-11.txt > diff/' + str(num) + '/5-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-12.txt > diff/' + str(num) + '/5-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-13.txt > diff/' + str(num) + '/5-13.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-14.txt > diff/' + str(num) + '/5-14.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/5/5-15.txt > diff/' + str(num) + '/5-15.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/6/6-1.txt > diff/' + str(num) + '/6-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/6/6-2.txt > diff/' + str(num) + '/6-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/6/6-3.txt > diff/' + str(num) + '/6-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-1.txt > diff/' + str(num) + '/7-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-2.txt > diff/' + str(num) + '/7-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-3.txt > diff/' + str(num) + '/7-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-4.txt > diff/' + str(num) + '/7-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-5.txt > diff/' + str(num) + '/7-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/all/7/7-6.txt > diff/' + str(num) + '/7-6.txt',shell=True)

def for_1(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-0.txt > diff/' + str(num) + '/1-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-1.txt > diff/' + str(num) + '/1-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-2.txt > diff/' + str(num) + '/1-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-3.txt > diff/' + str(num) + '/1-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-4.txt > diff/' + str(num) + '/1-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-5.txt > diff/' + str(num) + '/1-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-6.txt > diff/' + str(num) + '/1-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-7.txt > diff/' + str(num) + '/1-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-8.txt > diff/' + str(num) + '/1-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-9.txt > diff/' + str(num) + '/1-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-10.txt > diff/' + str(num) + '/1-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-11.txt > diff/' + str(num) + '/1-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-12.txt > diff/' + str(num) + '/1-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-13.txt > diff/' + str(num) + '/1-13.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-14.txt > diff/' + str(num) + '/1-14.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-15.txt > diff/' + str(num) + '/1-15.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-16.txt > diff/' + str(num) + '/1-16.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-17.txt > diff/' + str(num) + '/1-17.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-18.txt > diff/' + str(num) + '/1-18.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-19.txt > diff/' + str(num) + '/1-19.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-20.txt > diff/' + str(num) + '/1-20.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-21.txt > diff/' + str(num) + '/1-21.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-22.txt > diff/' + str(num) + '/1-22.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-23.txt > diff/' + str(num) + '/1-23.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-24.txt > diff/' + str(num) + '/1-24.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/1/1-25.txt > diff/' + str(num) + '/1-25.txt',shell=True)

def for_2(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-0.txt > diff/' + str(num) + '/2-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-1.txt > diff/' + str(num) + '/2-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-2.txt > diff/' + str(num) + '/2-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-3.txt > diff/' + str(num) + '/2-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-4.txt > diff/' + str(num) + '/2-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-5.txt > diff/' + str(num) + '/2-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-6.txt > diff/' + str(num) + '/2-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-7.txt > diff/' + str(num) + '/2-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-8.txt > diff/' + str(num) + '/2-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-9.txt > diff/' + str(num) + '/2-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/2/2-10.txt > diff/' + str(num) + '/2-10.txt',shell=True)

def for_3(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/for/3/3-0.txt > diff/' + str(num) + '/3-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/3/3-1.txt > diff/' + str(num) + '/3-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/3/3-2.txt > diff/' + str(num) + '/3-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/3/3-3.txt > diff/' + str(num) + '/3-3.txt',shell=True)

def for_4(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/for/4/4-0.txt > diff/' + str(num) + '/4-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/4/4-1.txt > diff/' + str(num) + '/4-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/4/4-2.txt > diff/' + str(num) + '/4-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/for/4/4-3.txt > diff/' + str(num) + '/4-3.txt',shell=True)

def while_1(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-0.txt > diff/' + str(num) + '/1-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-1.txt > diff/' + str(num) + '/1-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-2.txt > diff/' + str(num) + '/1-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-3.txt > diff/' + str(num) + '/1-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-4.txt > diff/' + str(num) + '/1-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-5.txt > diff/' + str(num) + '/1-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-6.txt > diff/' + str(num) + '/1-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-7.txt > diff/' + str(num) + '/1-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-8.txt > diff/' + str(num) + '/1-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-9.txt > diff/' + str(num) + '/1-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-10.txt > diff/' + str(num) + '/1-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-11.txt > diff/' + str(num) + '/1-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-12.txt > diff/' + str(num) + '/1-12.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-13.txt > diff/' + str(num) + '/1-13.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-14.txt > diff/' + str(num) + '/1-14.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-15.txt > diff/' + str(num) + '/1-15.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-16.txt > diff/' + str(num) + '/1-16.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-17.txt > diff/' + str(num) + '/1-17.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-18.txt > diff/' + str(num) + '/1-18.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-19.txt > diff/' + str(num) + '/1-19.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-20.txt > diff/' + str(num) + '/1-20.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-21.txt > diff/' + str(num) + '/1-21.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-22.txt > diff/' + str(num) + '/1-22.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-23.txt > diff/' + str(num) + '/1-23.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-24.txt > diff/' + str(num) + '/1-24.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/1/1-25.txt > diff/' + str(num) + '/1-25.txt',shell=True)

def while_2(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/while/2/2-0.txt > diff/' + str(num) + '/2-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/2/2-1.txt > diff/' + str(num) + '/2-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/2/2-2.txt > diff/' + str(num) + '/2-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/2/2-3.txt > diff/' + str(num) + '/2-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/2/2-4.txt > diff/' + str(num) + '/2-4.txt',shell=True)

def while_3(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-0.txt > diff/' + str(num) + '/3-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-1.txt > diff/' + str(num) + '/3-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-2.txt > diff/' + str(num) + '/3-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-3.txt > diff/' + str(num) + '/3-3.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-4.txt > diff/' + str(num) + '/3-4.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-5.txt > diff/' + str(num) + '/3-5.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-6.txt > diff/' + str(num) + '/3-6.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-7.txt > diff/' + str(num) + '/3-7.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-8.txt > diff/' + str(num) + '/3-8.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-9.txt > diff/' + str(num) + '/3-9.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-10.txt > diff/' + str(num) + '/3-10.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-11.txt > diff/' + str(num) + '/3-11.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/3/3-12.txt > diff/' + str(num) + '/3-12.txt',shell=True)

def while_4(file, num):
  subprocess.run('diff -U 0 ' + file + ' correct/while/4/4-0.txt > diff/' + str(num) + '/4-0.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/4/4-1.txt > diff/' + str(num) + '/4-1.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/4/4-2.txt > diff/' + str(num) + '/4-2.txt',shell=True)
  subprocess.run('diff -U 0 ' + file + ' correct/while/4/4-3.txt > diff/' + str(num) + '/4-3.txt',shell=True)